features/eu-debug: Update patches for eu-debug support
intel-gpu/xekmd-backports pull request #30
Opened 2024-11-29 10:26 UTC by smuqthya

Signed-off-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>

2024-12-03 10:30 UTC, ayazahma requested changes

2024-12-03 10:30 UTC, ayazahma commented on backport/patches/features/eu-debug/0001-ptrace-export-ptrace_may_access.patch
> -2.34.1
No need to modify this patch as part of update, no code chane

2024-12-03 10:30 UTC, ayazahma commented on backport/patches/features/eu-debug/0001-drm-ttm-Add-ttm_bo_access.patch
> +Signed-off-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
add branch details also like linux-next etc

2024-12-03 10:30 UTC, ayazahma commented on backport/patches/features/eu-debug/0001-drm-xe-Add-EUDEBUG_ENABLE-exec-queue-property.patch
>  ---
pls retain sign off of previous commiter

2024-12-03 10:43 UTC, hghimira approved these changes
Looks good for fw changes

2024-12-03 11:32 UTC, Dominisg commented on backport/patches/features/eu-debug/0001-drm-xe-eudebug-Prelim-rework-for-Xe-EU-debug.patch
+#define PRELIM_DRM_XE_EUDEBUG_EVENT_EXEC_QUEUE_PLACEMENTS 5
is wrong here. UMD does not agree with that change in prelim. Then wanted to have this event on the end of the list, so it should be:
+#define PRELIM_DRM_XE_EUDEBUG_EVENT_EXEC_QUEUE_PLACEMENTS 13

2024-12-04 10:27 UTC, Dominisg commented on backport/patches/features/eu-debug/0001-drm-xe-eudebug-Prelim-rework-for-Xe-EU-debug.patch
One another thing. I know from @tmistat that UMD requires this UAPI to be compliant with the one we have internally. Thus, I have a feeling that ioctls numbers should be the same. Here we have:
```
+#define PRELIM_DRM_XE_EUDEBUG_CONNECT 0x5f
+#define PRELIM_DRM_XE_DEBUG_METADATA_CREATE 0x5e
+#define PRELIM_DRM_XE_DEBUG_METADATA_DESTROY 0x5d
```
But in internal, there is:

```
#define PRELIM_DRM_XE_DEBUG_METADATA_DESTROY	0x5c
#define PRELIM_DRM_XE_DEBUG_METADATA_CREATE	0x5b
#define PRELIM_DRM_XE_EXEC_QUEUE_SET_PROPERTY	0x5a
#define PRELIM_DRM_XE_EUDEBUG_CONNECT		0x59
```

2024-12-04 13:46 UTC, Dominisg commented on backport/patches/features/eu-debug/0001-drm-xe-eudebug-Prelim-rework-for-Xe-EU-debug.patch
Scratch what is above. We confirmed with UMD folks that they want the numbering to stay the same.

2024-12-04 14:42 UTC, ayazahma commented on backport/patches/features/eu-debug/0001-drm-xe-eudebug-Prelim-rework-for-Xe-EU-debug.patch
@Dominisg , does it means that 
1.
 _+#define PRELIM_DRM_XE_EUDEBUG_EVENT_EXEC_QUEUE_PLACEMENTS 5
is wrong here. UMD disagrees with that change in prelim. Then wanted to have this event on the end of the list, so it should be:
+#define PRELIM_DRM_XE_EUDEBUG_EVENT_EXEC_QUEUE_PLACEMENTS 13__

We Need to take as review comment and update PR , is it correct?

2.
 One another thing. I know from @tmistat that UMD requires this UAPI to be compliant with the one we have internally. Thus, I have a feeling that ioctls numbers should be the same. Here we have:

_+#define PRELIM_DRM_XE_EUDEBUG_CONNECT 0x5f
+#define PRELIM_DRM_XE_DEBUG_METADATA_CREATE 0x5e
+#define PRELIM_DRM_XE_DEBUG_METADATA_DESTROY 0x5d
But in internal, there is:

#define PRELIM_DRM_XE_DEBUG_METADATA_DESTROY	0x5c
#define PRELIM_DRM_XE_DEBUG_METADATA_CREATE	0x5b
#define PRELIM_DRM_XE_EXEC_QUEUE_SET_PROPERTY	0x5a
#define PRELIM_DRM_XE_EUDEBUG_CONNECT		0x59_

This needs to be ignored. is it correct?

2024-12-04 15:16 UTC, tmistat commented on backport/patches/features/eu-debug/0001-drm-xe-eudebug-Prelim-rework-for-Xe-EU-debug.patch
the definition of 
#define PRELIM_DRM_XE_EUDEBUG_EVENT_EXEC_QUEUE_PLACEMENTS 
has to be aligned with these two 
https://github.com/intel-innersource/drivers.gpu.linux-xe.kernel/pull/1001/files
https://github.com/Intel-Habana-collab/drivers.gpu.linux-xe.kernel/pull/842/files#diff-640e77fc09ee750479a14706a032e44f2e5928052f2f524f3ff0dd1e3f26c316

2024-12-04 15:24 UTC, tmistat commented on backport/patches/features/eu-debug/0001-drm-xe-eudebug-Prelim-rework-for-Xe-EU-debug.patch
and comment to ad2 
yes we cant guarantee same id of prelim ioct across multiple kernel trees 
as there are another features  in prelim state that land independently to collab and do not land into kobuk

2024-12-04 21:05 UTC, bmyates commented on backport/patches/features/eu-debug/0001-drm-xe-eudebug-Prelim-rework-for-Xe-EU-debug.patch
From UMD side we want the IOCTL numbers to stay consistent within a single code tree.   If they are different in kobuk vs xe-internal,  that is okay.   

Preferably habana and xe-internal would be exactly the same.

2024-12-05 08:19 UTC, ayazahma approved these changes
UAPI Approved by @Dominisg / @tmistat.

2024-12-05 08:19 UTC, merged

2024-12-06 03:57 UTC, ayazahma commented on backport/patches/features/eu-debug/0001-drm-xe-eudebug-Prelim-rework-for-Xe-EU-debug.patch
well as in my view, we should have the same ioctl number for prelim irrespective of tree.
It may be late for this time however, let plan to align in future, as there is no other consumer then its much easier to correct it in next plan released